//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "ISBN Number can't be empty!")]
        public string ISBN { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a Book Title!")]
        public string Title { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Book Edition is Required!")]
        public string Edition { get; set; }
        public string Description { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Author's Name!")]
        public string Author { get; set; }
        [Display(Name = "Category ID")]
        [Range(1, int.MaxValue, ErrorMessage = "Category ID can't be '0'!")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Category ID can't be empty!")]
        public int CategoryIDFK { get; set; }
        [Display(Name = "Publisher ID")]
        [Range(1, int.MaxValue, ErrorMessage = "Publisher ID can't be '0'!")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Publisher ID can't be empty!")]
        public int PublisherIDFK { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Quantity can't be '0'!")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter the number of books!")]
        public int Quantity { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Price can't be '0.00'!")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Book Price is Required!")]
        public decimal Price { get; set; }
    }
}
